#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings

use List::Util qw/sum/;

our $scores = '37';
our ($input) = map { chomp; $_; } <>;

my @elves = (0, 1);                     # Position within the $scores string
while (length($scores) <= $input + 10) {
    # Append new scores
    $scores .= sum map { substr($scores, $_, 1) } @elves;
    # Update the @elves pointers
    $_ = ($_ + 1 + substr($scores, $_, 1)) % length($scores) foreach @elves;
}
say substr($scores, $input, 10);
