#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings

use List::Util qw/sum/;

our $scores = '37';
our ($search) = map { chomp; $_; } <>;

my @elves = (0, 1);                     # Position within the $scores string
while ($scores !~ /${search}/g) {       # Use /g to preserve position
    # Append new scores
    $scores .= sum map { substr($scores, $_, 1) } @elves;
    # Update the @elves pointers
    $_ = ($_ + 1 + substr($scores, $_, 1)) % length($scores) foreach @elves;
    # Optimization: don't bother re-searching past stuff
    pos $scores = -length($search) - 1;
}
say pos($scores) - length($search);
