#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

my $count = 0;
while (<>) {
    my ($min, $max, $letter, $pass) = m/^(\d+)-(\d+) (\w): (\w+)$/;
    my $matches = () = $pass =~ m/${letter}/g;
    $count++ if $min <= $matches and $matches <= $max;
}
print "${count}\n";
