#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings

our %input;

# Parse input
foreach (map { [ m/(\d+)/g ]} <>) {
    my ($i, @connections) = @$_;
    $input{$i} = \@connections;
}

my $groups = 0;
while (%input) {
    # Traverse the pipes
    my (@queue) = (sort keys %input)[0];
    my %seen;
    while (@queue) {
        my $this = shift @queue;
        next if $seen{$this}++;
        push @queue, @{ $input{$this} };
        delete $input{$this};
    }
    $groups++;
}
say $groups;
