#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings
use List::Util qw/max/;

our ($num_players, $last_marble) =
    map { m/(\d+) players; last marble is worth (\d+) points/ } <>;

$last_marble *= 100;

# This solution assumes the current position is always at index 0, and only
# manipulates the ends of the list. (Unlike the original solution which moves
# the pointer around and manipulates the middle of the list.) Perl is fast at
# manipulating the ends of a list, but slow manipulating the middle. So, while
# this solution is perhaps not as fast as a doubly-linked list would be, it was
# a lot easier to implement. And it runs in just a few seconds. Good Enough.

my @scores;
my @circle = (0);
for (my $marble = 1; $marble <= $last_marble; $marble++) {
    if ($marble % 23) {
        my @chunk = splice(@circle, 0, 2 % @circle);
        push @circle, @chunk;
        unshift @circle, $marble;
    } else {
        my @chunk = splice(@circle, -(7 % @circle));
        unshift @circle, @chunk;
        $scores[$marble % $num_players] += $marble + shift @circle;
    }
}
say max(grep { defined } @scores);
