#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings
use List::Util qw/max/;

our ($num_players, $last_marble) =
    map { m/(\d+) players; last marble is worth (\d+) points/ } <>;

$last_marble *= 100;

my @scores;
my @circle = (0);       # Assume index 0 is the current marble
for (my $marble = 1; $marble <= $last_marble; $marble++) {
    if ($marble % 23) {
        my @chunk = splice(@circle, 0, 2 % @circle);
        push @circle, @chunk;
        unshift @circle, $marble;
    } else {
        my @chunk = splice(@circle, -(7 % @circle));
        unshift @circle, @chunk;
        $scores[$marble % $num_players] += $marble + shift @circle;
    }
}
say max(grep { defined } @scores);
