#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

# Read ordering rules
our %rules;
while (<>) {
    last if not m/^(\d+)\|(\d+)$/;
    my $key = qr/(?=.*\b$1\b)(?=.*\b$2\b)/;
    my $val = qr/\b$1\b.+\b$2\b/;
    $rules{$key} = $val;
}

my $mids = 0;
 OUTER:
    # Read page numbers for each update
    foreach my $line (<>) {
        # Make sure this line is valid
        foreach my $key (grep { $line =~ /$_/ } keys %rules) {
            next OUTER if $line !~ /${rules{$key}}/;
        }

        # Save the middle value
        my (@numbers) = split /,/, $line;
        $mids += $numbers[$#numbers / 2];
    }

print "${mids}\n";
