#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

my %max = ('red' => 12, 'green' => 13, 'blue' => 14);
my $sum = 0;

# Trying to minimize variables here just to be obtuse/clever
LINE: while (<>) {
    chomp;
    foreach my $href (map { { reverse m/(\d+) (\w+)/g } }
                      split /;/, (split /:/)[1]) {
        while (my ($key, $val) = each %$href) {
            next LINE if $val > $max{$key};
        }
    }

    $sum += (m/^Game (\d+):/)[0];
}
print "${sum}\n";


#    use Data::Dumper qw//; $Data::Dumper::Sortkeys = 1;
#    print Data::Dumper->Dump([ \@data ], [ '*data' ]); exit;
