#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

my $sum = 0;
foreach (map { chomp; split /,/; } <>) {
    my ($first, $last) = split /-/;

    # Can't have odd numbers of digits
    $first = 10 ** length($first) if length($first) % 2 == 1;
    $last = 10 ** (length($last) - 1) - 1 if length($last) % 2 == 1;
    next if $first > $last;

    for (my $i = $first; $i <= $last; $i++) {
        $sum += $i if $i =~ m/^(.+)\g{1}$/;
    }
}
print "${sum}\n";
