#!/usr/bin/perl

use v5.36.0;

my %grid;
while (<>) {
    my ($x0, $y0, $wide, $tall) = m/^#\d+ @ (\d+),(\d+): (\d+)x(\d+)$/;
    # Not the most efficient way, but works for this scale
    foreach my $x ($x0..$x0+$wide-1) {
        foreach my $y ($y0..$y0+$tall-1) {
            $grid{"${x},${y}"}++;
        }
    }
}
say scalar grep { $_ > 1 } values %grid;
