#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings

our %registers;
our $big = -(~0 >> 1)-1;        # Assume the worst

while (<>) {
    chomp;
    # Just convert the input into Perl
    s/inc/+=/;
    s/dec/-=/;
    s/(\d if )([a-z]+)/$1\$registers{$2}/;
    s/^([a-z]+)/\$registers{$1}/;
    # And evaluate it!
    eval;
    my $new_big = (sort { $a <=> $b } values %registers)[-1];
    $big = $new_big if $new_big > $big;
}

say $big;
