#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';





#use Data::Dumper qw//; $Data::Dumper::Sortkeys = 1; #$Data::Dumper::Useqq = 1;
#print Data::Dumper->Dump([$foo, $bar], ['*foo', '*bar']);
