#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

my (@stones) = map { chomp; split / /; } <>;

sub mapping {
    my ($stone) = @_;
    my $len = length($stone);

    $stone eq 0   and do { return 1; };
    $len % 2 == 0 and do { my $one = int($stone / 10**($len/2));
                           my $two = $stone - $one * 10**($len/2);
                           return ($one, $two); };
    return $stone * 2024;
}

foreach (1..25) {
    @stones = map { &mapping($_) } @stones;
}

print scalar(@stones), "\n";
