#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings

my $valid = 0;
while (<>) {
    chomp;
    my %words;
    $words{$_}++ foreach split /\s+/;
    $valid++ if not grep { $_ > 1 } values %words;
}
say $valid;
