#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings
use List::Util qw/sum/;

our @input = (sort { $$a[0] <=> $$b[0] or $$a[1] <=> $$b[1] }
              map { [ map { int } split /,/ ] } <>);

my ($min_x, $max_x) = ($input[0][0], $input[-1][0]);
my ($min_y, $max_y) = (sort { $a <=> $b } map { $$_[1] } @input)[0,-1];

my $counter = 0;
foreach my $x ($min_x..$max_x) {
    foreach my $y ($min_y..$max_y) {
        my $sum = sum(map { (abs($input[$_][0] - $x) +
                             abs($input[$_][1] - $y)) }
                      0..$#input);
        $counter++ if $sum < 10000;
    }
}
say $counter;
