#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings

our @input = (sort { $$a[0] <=> $$b[0] or $$a[1] <=> $$b[1] }
              map { [ map { int } split /,/ ] } <>);

my ($min_x, $max_x) = ($input[0][0], $input[-1][0]);
my ($min_y, $max_y) = (sort { $a <=> $b } map { $$_[1] } @input)[0,-1];

# Each entry of @input will have a corresponding @counters to track how often
# that input point was closest. If the point being checked is on an edge, the
# closest input point will also be tracked in %edges so it can be excluded.
my (@counters, %edges);
foreach my $x ($min_x..$max_x) {
    foreach my $y ($min_y..$max_y) {
        # Find the 2 closest points
        my ($d1, $d2) = (sort { $$a[0] <=> $$b[0] }
                         # Associate Manhattan distance to the point reference
                         map { my $d = (abs($input[$_][0] - $x) +
                                        abs($input[$_][1] - $y));
                               [ $d, $_ ] }
                         0..$#input);
        next if $$d1[0] == $$d2[0];     # Equidistant points, ignore
        $counters[ $$d1[1] ]++;
        # Keep track of edges
        $edges{ $$d1[1] }++
            if $x == $min_x or $x == $max_x or $y == $min_y or $y == $max_y;
    }
}

my $largest = ( sort { $a <=> $b }
                map { $counters[$_] }           # Extract the area
                grep { not exists $edges{$_} }  # Exclude infinite areas
                0..$#counters )[-1];
say $largest;
