#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings

# Read input
my ($min_x, $min_y) = (~0) x 2;
my ($max_x, $max_y) = (0) x 2;
my @input;
while (<>) {
    # Parse 2 ranges, $x0..$x1 and $y0..$y1
    m/x=(?<x>[\d.]+), y=(?<y>[\d.]+)|y=(?<y>[\d.]+), x=(?<x>[\d.]+)/;
    my ($x0, $x1) = split /\.\./, $+{'x'};  # Split ranges
    my ($y0, $y1) = split /\.\./, $+{'y'};
    $x1 //= $x0;                            # Ensure upper bounds are defined
    $y1 //= $y0;

    # Adjust known minimums and maximums
    $min_x = $x0 if $x0 < $min_x; $max_x = $x1 if $x1 > $max_x;
    $min_y = $y0 if $y0 < $min_y; $max_y = $y1 if $y1 > $max_y;

    # Save delimiters
    push @input, [$x0, $x1, $y0, $y1];
}

# Shift coordinates so the lowest x and y are each 1
my ($delta_x, $delta_y) = ($min_x - 1, $min_y - 1);
my ($water_x, $water_y) = (500 - $delta_x, 0);
$min_x -= $delta_x; $max_x -= $delta_x;
$min_y -= $delta_y; $max_y -= $delta_y;
foreach (@input) {
    $$_[0] -= $delta_x; $$_[1] -= $delta_x;
    $$_[2] -= $delta_y; $$_[3] -= $delta_y;
}

# Create the grid, as a series of strings.
my @grid = map { '.' x ($max_x+2) . "\n" } 0..$max_y;       # Fill it with sand
substr $grid[$water_y], $water_x, 1, '+';                   # Add water fountain
foreach my $vein (@input) {                                 # Add clay veins
    my ($x0, $x1, $y0, $y1) = @$vein;
    foreach my $y ($y0..$y1) {
        my $len = $x1 - $x0 + 1;
        substr $grid[$y], $x0, $len, ('#') x $len;
    }
}
# Collapse the grid into a single string
my $grid = join('', @grid);

# Simulate the flowing spring with lookaround assertion regexes
my $len = index $grid, "\n";                                    # Line length
1 while ($grid =~ s/[+|].{$len}\K\./|/gos ||                    # Flow down
         $grid =~ s/\.(?=\|.{$len}[#~])/|/gos ||                # Flow left
         $grid =~ s/\|\K\.(?=.{@{[$len-1]}}[#~])/|/gos ||       # Flow right
         $grid =~ s/[#~]\K\|(?=\|*#)(?=.{$len}[#~])/~/gos);     # Still water
# Tally how much still water 
my $still =()= $grid =~ m/~/g;
#print $grid;
say $still;
