#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings

# Read input
my ($min_x, $min_y) = (~0) x 2;
my ($max_x, $max_y) = (0) x 2;
my @input;
while (<>) {
    # Parse 2 ranges, $x0..$x1 and $y0..$y1
    m/x=(?<x>[\d.]+), y=(?<y>[\d.]+)|y=(?<y>[\d.]+), x=(?<x>[\d.]+)/;
    my ($x0, $x1) = split /\.\./, $+{'x'};  # Split ranges
    my ($y0, $y1) = split /\.\./, $+{'y'};
    $x1 //= $x0;                            # Ensure upper bounds are defined
    $y1 //= $y0;

    # Adjust known minimums and maximums
    $min_x = $x0 if $x0 < $min_x; $max_x = $x1 if $x1 > $max_x;
    $min_y = $y0 if $y0 < $min_y; $max_y = $y1 if $y1 > $max_y;

    # Save delimiters
    push @input, [$x0, $x1, $y0, $y1];
}

# Shift coordinates so the lowest x and y are each 1
my ($delta_x, $delta_y) = ($min_x - 1, $min_y - 1);
my ($water_x, $water_y) = (500 - $delta_x, 0);
$min_x -= $delta_x; $max_x -= $delta_x;
$min_y -= $delta_y; $max_y -= $delta_y;
foreach (@input) {
    $$_[0] -= $delta_x; $$_[1] -= $delta_x;
    $$_[2] -= $delta_y; $$_[3] -= $delta_y;
}

# Create the grid, as a series of strings.
my @grid = map { '.' x ($max_x+2) . "\n" } 1..($max_y+1);   # Fill it with sand
substr $grid[$water_y], $water_x, 1, '+';                   # Add water fountain
foreach my $vein (@input) {                                 # Add clay veins
    my ($x0, $x1, $y0, $y1) = @$vein;
    foreach my $y ($y0..$y1) {
        my $len = $x1 - $x0 + 1;
        substr $grid[$y], $x0, $len, ('#') x $len;
    }
}
# Collapse the grid into a single string
my $grid = join('', @grid);

# Simulate the flowing spring with lookaround assertion regexes
my $len = index $grid, "\n";                                    # Line length
1 while ($grid =~ s/[+|].{$len}\K\./|/gos ||                    # Flow down
         $grid =~ s/\.(?=\|.{$len}[#~])/|/gos ||                # Flow left
         $grid =~ s/\|\K\.(?=.{@{[$len-1]}}[#~])/|/gos ||       # Flow right
         $grid =~ s/[#~]\K\|(?=\|*#)(?=.{$len}[#~])/~/gos);     # Still water
# Tally how much still water 
my $still =()= $grid =~ m/~/g;
#print $grid;
say $still;

__DATA__

Some rambling thoughts on regex:

The crux of the program is to simulate water flow. Regex is perhaps not the
most efficient tool for this exact situation. But, it can accomplish the goal
in a way that is not terribly difficult to understand--for one who knows a bit
of regex, anyway, an admittedly obtuse topic for the uninitiated.

There are two versions of the regexes used for this puzzle. The regexes used in
Part 1 are a capturing version lifted from a Reddit comment:
    https://www.reddit.com/r/adventofcode/comments/a6wpup/comment/ec059u5/

However, the found version had a bug in the 4th regex that caused it to fail
with my input. The problem could be seen if water spilled from one or more bins
above and the spaces between bins was completely filled by flowing water. As in,
this scenario:
    ......|........|.......
    ....#|||||||...|.......
    ....#~~~~~#|||||||#....
    ....#~~~~~#||#~~~~#....   <-- These 3 lines where "#||#" appears are
    ....#~~~~~#||#~~~~#....   <-- erroneously rendered as "#~~#" by the
    ....#######||######....   <-- original regex from Reddit.
    ...........||..........

The original regex would make a mistake between the clay bins in this instance,
replacing flowing water with still water when there's nothing solid to support
the still water. I corrected that oversight with a lookahead assertion. I also
removed backslash escapes from a few places where they were unnecessary, and
consolidated captures where possible. The result looks like this:

1 while ($grid =~ s/[+|].{$len}\K\./|/gos ||                    # Flow down
         $grid =~ s/\.(\|.{$len}[\#~])/|$1/gos ||               # Flow left
         $grid =~ s/\|\.(.{@{[$len-1]}}[\#~])/||$1/gos ||       # Flow right
         $grid =~ s/([#~])\|(?=.{$len}[#~])(\|*#)/$1~$2/gos);   # Still water

That code works just fine, but i wasn't happy with it since it is not my
original work. So, i wrote a different version that uses lookaround assertions
rather than capturing. That version is presented in the code above for Part 2.
Intuition tells me the lookaround version should be faster since the regex
engine doesn't have to do capturing work. Alas, intuition is often wrong and in
truth the lookaround version is slower by a factor of 2⅓. Still, it is what i
went with for Part 2 because it is my own invention.

Since the workings of it all looks like a bunch of line noise, a heavily
commented version has been provided below.

# Lookaround assertion version, with expanded comments
1 while (# Flow down: Look for flowing water that has sand directly below, then
         # replace that sand with flowing water.
         $grid =~ s/[+|]        # Match the source spring or flowing water
                    .{$len}     # Match quantity $len characters--an entire line
                    \K          # Move the cursor here; disregard stuff before
                    \.          # Match a sand character, '.'
                    /|/gosx ||  # Replace the sand with flowing water, '|'
         # Flow left: Look for sand that has flowing water immediately to its
         # right, and something water may flow over (clay or still water) below
         # that flowing water.
         $grid =~ s/\.          # Sand character, '.'
                    (?=         # Begin a zero-width lookahead assertion
                       \|       # Flowing water, '|'
                       .{$len}  # Skip to the next line
                       [#~]     # What water may flow over: clay or still water
                    )           # Close the lookahead
                    /|/gosx ||  # Replace the sand with flowing water, '|'
         # Flow right: Look for sand that has flowing water immediately to its
         # left, and has something water may flow over below that flowing water.
         $grid =~ s/\|          # Match flowing water
                    \K          # Set position here, disregarding earlier match
                    \.          # Sand character, '.'
                    (?=         # Begin lookahead assertion
                       .{@{[$len-1]}}   # Move ahead 1 line, minus 1 character
                       [#~]     # What water may flow over: clay or still water
                    )           # Close lookahead assertion
                    /|/gosx ||  # Replace the sand with flowing water, '|'
         # Still water: Look for clay or still water followed by flowing water
         # that is then followed by 1) flowing water and a clay wall (basically,
         # we're looking for the situation where we're inside a clay wall
         # container) and 2) there is clay or still water below the flowing
         # water, which is also necessary to let the water be still.
         $grid =~ s/[#~]        # What water flows over: clay or still water
                    \K          # Set position here, disregarding earlier match
                    \|          # Match flowing water
                    (?=         # Begin lookahead assertion
                       \|*      # 0 or more flowing water characters,
                       \#       # then a clay wall (escaped due to x modifer)
                    )           # Close lookahead assertion
                    (?=         # Begin another lookahead assertion (same pos)
                       .{$len}  # Move ahead one line
                       [#~]     # What water may flow over: clay or still water
                    )           # Close lookahead assertion
                    /~/gosx);   # Replace flowing water with still water, '~'
