#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings
use List::Util qw/sum/;

our @data = map { int } map { chomp; split // } <>;

say int sum map { $data[$_] } grep { $data[$_] == $data[($_+1)%@data] } 0..$#data;
