#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings
use Algorithm::Combinatorics qw/combinations/;
use List::Util qw/sum/;

# One-liner solution:
say sum (map { $$_[1] / $$_[0] }
         grep { $$_[1] % $$_[0] == 0 }
         map { combinations($_, 2) }
         map { chomp; [ sort { $a <=> $b } split /\s+/ ] } <>);
