#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings

our @data = map { chomp; [ sort { $a <=> $b } split /\s+/ ] } <>;
my $sum = 0;
foreach (@data) {
  WHILE:
    while (@$_) {
        my $compare = pop @$_;
        foreach (@$_) {
            if ($compare % $_ == 0) {
                $sum += $compare / $_;
                last WHILE;
            }
        }
    }
}
say $sum;
