#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings
use Scalar::Util qw/looks_like_number/;

our ($data) = map { chomp; int; } <>;

# This extra lookup table was sourced from:  https://oeis.org/A141481
open(my $fh, '<', 'b141481.txt');
while (<$fh>) {
    chomp;
    my $n = (split /\s/)[1];
    next if not looks_like_number($n);
    next if $n <= $data;

    say $n;
    exit;
}
