#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings

while (<>) {
    chomp;

    s/<(?:!.|[^>!]*)*>//g;      # Clear the garbage
    tr /{}//cd;                 # Clear non-grouping characters

    # Process the groups
    my ($sum, $depth) = (0) x 2;
    foreach (split //) {
        /\{/ and do { $sum += ++$depth; };
        /\}/ and do { $depth--; };
    }

    say $sum;
}
