#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings

while (<>) {
    chomp;

    1 while s/(<[^>!]*?)!./$1/; # Process cancelations

    # Count the garbage
    my $sum = 0;
    $sum += length($1) while s/<([^>]*)>//;

    say $sum;
}
