#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

our %scores = (
    #                 Opponent, Us       -> Outcome
    'A X' => 3 + 0, # Rock,     Scissors -> loss
    'A Y' => 1 + 3, # Rock,     Rock     -> tie
    'A Z' => 2 + 6, # Rock,     Paper    -> win
    'B X' => 1 + 0, # Paper,    Rock     -> loss
    'B Y' => 2 + 3, # Paper,    Paper    -> tie
    'B Z' => 3 + 6, # Paper,    Scissors -> win
    'C X' => 2 + 0, # Scissors, Paper    -> loss
    'C Y' => 3 + 3, # Scissors, Scissors -> tie
    'C Z' => 1 + 6  # Scissors, Rock     -> win
);

my $total = 0;
while (<>) {
    chomp;
    $total += $scores{$_};
}
print "${total}\n";
