#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings

# Read input
our @input = map { m/pos=<([-,\d]+)>, r=(\d+)/; [ split(/,/, $1), $2 ] } <>;

# Find index of the nanobot with the maximum radius
my $i = 0;
foreach (1..$#input) {
    $i = $_ if $input[$i][3] < $input[$_][3];
}

# Get info on the strongest nanobot
my ($x, $y, $z, $r) = @{$input[$i]};

# Count nanobots that are within range
my $count = 0;
foreach (@input) {
    my ($x1, $y1, $z1) = @$_;
    $count++ if abs($x1-$x) + abs($y1-$y) + abs($z1-$z) <= $r;
}

say $count;
