#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings

#our @list = (0..4);     # sample
our @list = (0..255);   # real data

our @lengths = map { ord } map { chomp; split // } <>;
push @lengths, 17, 31, 73, 47, 23;

my $position = 0;
my $skipsize = 0;

foreach my $round (1..64) {
    foreach my $length (@lengths) {
        my (@positions) = map { $_ % @list } $position..($position+$length-1);
        @list[@positions] = reverse @list[@positions];
        $position += $length + $skipsize;
        $skipsize++;
    }
}

my @dense_hash;
while (my (@chunk) = splice @list, 0, 16) {
    push @dense_hash, 0;
    $dense_hash[-1] ^= $_ foreach @chunk;
}

say map { sprintf '%02x', $_ } @dense_hash;
