#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

my $count = 0;
my $previous = <>;
while (my $current = <>) {
    $count++ if $current > $previous;
    $previous = $current;
}
print "${count}\n";
