#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

# Parse input
my @times = split / +/, (<> =~ m/^Time: *([ \d]+)$/)[0];
my @distances = split / +/, (<> =~ m/^Distance: *([ \d]+)$/)[0];

my @wins = ();
foreach (my $i = 0; $i < @times ; $i++) {
    # Loop over how long we hold the button
    push @wins, scalar grep { ($_ * ($times[$i] - $_)) > $distances[$i] } 0..$times[$i];
}

my $total = 1;
$total *= $_ foreach @wins;
print "${total}\n";
