#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

# Parse input
(my $time = (<> =~ m/^Time: *([ \d]+)$/)[0]) =~ s/ //g;
(my $distance = (<> =~ m/^Distance: *([ \d]+)$/)[0]) =~ s/ //g;

# A pure brute-force solution, no optimization
my $wins = 0;
for (my $i = 0; $i <= $time; $i++) {
    $wins++ if ($i * ($time - $i)) > $distance;
}
print "${wins}\n";
