#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

# Parse input
my ($times) = <> =~ m/^Time: *([ \d]+)$/;
my @times = split / +/, $times;
my ($distances) = <> =~ m/^Distance: *([ \d]+)$/;
my @distances = split / +/, $distances;

my @wins = ();
foreach (my $i = 0; $i < @times ; $i++) {
    my $time = $times[$i];
    my $distance = $distances[$i];
    # Loop over how long we hold the button
    push @wins, scalar grep { ($_ * ($time - $_)) > $distance } 0..$time;
}

my $total = 1;
$total *= $_ foreach @wins;
print "${total}\n";
