#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

# Parse input
(my $time = <>) =~ s/[^\d]+//g;
(my $distance = <>) =~ s/[^\d]+//g;

# A pure brute-force solution, no optimization, more idiomatic solution
my $wins = scalar grep { ($_ * ($time - $_)) > $distance } 0..$time;
print "${wins}\n";
