#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

# Parse input
(my $time = <>) =~ s/[^\d]+//g;
(my $distance = <>) =~ s/[^\d]+//g;

# Find the first and last winning races using the quadratic formula
my $first = int(($time - sqrt($time ** 2 - 4 * $distance)) / 2);
my $last = int(($time + sqrt($time ** 2 - 4 * $distance)) / 2);

print $last-$first,"\n";
