#!/usr/bin/perl

use 5.14.1;
use strict;
use warnings 'all';
use experimental 'smartmatch';

my $sum = 0;
while (<>) {
    chomp;
    s/^.*\|\s*//;
    $sum += scalar grep { length($_) ~~ [2, 3, 4, 7] } split / /;
}
print "${sum}\n";
