#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings

use List::Util qw/sum/;

our @input = map { int } map { chomp; split / / } <>;

my $i = 0;
sub parse {
    my ($num_children, $num_metadata) = splice(@input, 0, 2);
    my $index = $i++;

    my @children;
    while ($num_children) {
        $num_children--;
        push @children, &parse;
    }
    my @metadata = splice(@input, 0, $num_metadata);

    if (@children) {
        my $sum = 0;
        $sum += $children[$_ - 1] // 0 foreach @metadata;
        return $sum;
    } else {
        return sum @metadata;
    }
}

say &parse;
