#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings

our @data = map { int } map { chomp; split /\s+/; } <>;

my %seen;
my $cycles = 0;
while (1) {
    my $key = join("\t", @data);
    if (exists $seen{$key}) {
        say $cycles - $seen{$key};
        last;
    }
    $seen{$key} = $cycles;

    # Find index of the largest value
    my $max_index = 0;
    for (my $i = 1; $i < @data; $i++) {
        $max_index = $i if $data[$i] > $data[$max_index];
    }

    # Redistribute it
    my $value = $data[$max_index];
    $data[$max_index] = 0;
    while ($value) {
        $data[++$max_index % @data]++;
        $value--;
    }

    $cycles++;
}
