#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

# Functions with obvious names
sub max { return (sort { $a <=> $b } @_)[-1]; }
sub min { return (sort { $a <=> $b } @_)[0]; }

my %points;
while (<>) {
    my ($x1, $y1, $x2, $y2) = m/(\d+)/g;
    if ($x1 == $x2) {
        my ($min, $max) = (&min($y1, $y2), &max($y1, $y2));
        $points{$_}++ foreach map { "${x1},$_" } $min..$max;
    } elsif ($y1 == $y2) {
        my ($min, $max) = (&min($x1, $x2), &max($x1, $x2));
        $points{$_}++ foreach map { "$_,${y1}" } $min..$max;
    }
}

print scalar(grep { $_ > 1 } values %points), "\n";
