#!/usr/bin/perl

my %map1 = (
    'eighthree' => 83,
    'eightwo' => 82,
    'fiveight' => 58,
    'nineight' => 98,
    'oneight' => 18,
    'sevenine' => 79,
    'threeight' => 38,
    'twone' => 21
);
my %map2 = (
    'one' => 1,
    'two' => 2,
    'three' => 3,
    'four' => 4,
    'five' => 5,
    'six' => 6,
    'seven' => 7,
    'eight' => 8,
    'nine' => 9
);

my $pattern1 = join("|",keys %map1);
my $pattern2 = join("|",keys %map2);

my $sum = 0;
while (<>) {
    s/(${pattern1})/$map1{$1}/g;
    s/(${pattern2})/$map2{$1}/g;
    s/^[^\d]*(?=(\d))|.*(\d)[^\d]*$/\1\2/g;
    $sum += $_;
}
print "${sum}\n";
