#!/usr/bin/perl

my %map = (
    'eighthree' => 83,
    'eightwo' => 82,
    'fiveight' => 58,
    'nineight' => 98,
    'oneight' => 18,
    'sevenine' => 79,
    'threeight' => 38,
    'twone' => 21,
    'one' => 1,
    'two' => 2,
    'three' => 3,
    'four' => 4,
    'five' => 5,
    'six' => 6,
    'seven' => 7,
    'eight' => 8,
    'nine' => 9
);

my $sum = 0;
while (<>) {
    s/(eighthree|eightwo|fiveight|nineight|oneight|sevenine|threeight|twone|one|two|three|four|five|six|seven|eight|nine)/$map{$1}/g;
    s/^[^\d]*(?=(\d))|.*(\d)[^\d]*$/\1\2/g;
    $sum += $_;
}
print "${sum}\n";
