#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

# Direct translation of the problem description. Works great, but kind of slow.

# ------------------------------------------------------------------------------
#  Implementation of the trivial formulae
# ------------------------------------------------------------------------------
sub mix { $_[0] ^ $_[1] }
sub prune { $_[0] % 16777216 }
sub evolve {
    my ($secret) = @_;
    $secret = &prune(&mix($secret, $secret * 64));
    $secret = &prune(&mix($secret, int($secret / 32)));
    $secret = &prune(&mix($secret, $secret * 2048));
    return $secret;
}

my $sum = 0;
foreach my $secret (map { chomp; $_; } <>) {
    $secret = &evolve($secret) for 1..2000;
    $sum += $secret
}
print "${sum}\n";
