#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

our @grid = map { chomp; [ split // ] } <>;

sub trees {
    my ($row_delta, $col_delta) = @_;

    my $trees = 0;
    my ($row, $col) = (0, 0);
    while ($row < @grid) {
        $trees++ if $grid[$row][$col] eq '#';
        $row += $row_delta;
        $col += $col_delta; $col %= scalar @{$grid[0]};
    }
    return $trees;
}

my $product = 1;
$product *= &trees(@$_) foreach ([1, 1], [1, 3], [1, 5], [1, 7], [2, 1]);
print "${product}\n";
