#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

# Solve the given sub-expression. Assumes no internal parentheses.
sub math {
    my ($arg) = @_;
    $arg =~ tr/()//d;
    my (@tokens) = split / /, $arg;
    @tokens = (eval join('', @tokens[0..2]), @tokens[3..$#tokens])
        while @tokens > 1;
    return $tokens[0];
}

my $sum = 0;
foreach my $expr (map { chomp; "($_)" } <>) {
    # Replace parenthesized expressions with their value
    1 while ($expr =~ s/(\([^()]+\))/${\&math($1)}/);
    $sum += $expr;
}
print "${sum}\n";
