#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

my $count = 0;
while (<>) {
    my ($lower1, $upper1, $lower2, $upper2) = m/(\d+)/g;
    $count++ if (($lower1 <= $lower2 and $upper1 >= $upper2) or
                 ($lower1 >= $lower2 and $upper1 <= $upper2));
}
print "${count}\n";
