#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

# This version is very straightforward, in a traditional style similar to C.

our @cubes = map { chomp; [ map { int } split /,/ ] } <>;

# Total area of all the cubes
our $area = 6 * @cubes;

# Now identify which sides intersect, and subtract those areas from the total.
for (my $i = 0; $i < $#cubes; $i++) {
    for (my $j = $i+1; $j <= $#cubes; $j++) {
        my $sum = (abs($cubes[$i][0] - $cubes[$j][0]) +
                   abs($cubes[$i][1] - $cubes[$j][1]) +
                   abs($cubes[$i][2] - $cubes[$j][2]));
        $area -=2 if $sum == 1;
    }
}

print "${area}\n";
