#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings

our %deps;      # Track dependencies
our %seen;      # Track letters that have been seen

foreach (map { [ m/Step (\w) must be finished before step (\w) can begin./ ] } <>) {
    my ($one, $two) = @$_;
    @seen{$one, $two} = ();
    $deps{$two}{$one} = ();
}

our %avail;     # Letters currently available
@avail{ grep { not exists $deps{$_} } keys %seen } = ();

my $order = '';
while (%avail) {
    # Select the next letter from those available
    my $letter = (sort keys %avail)[0];
    # Mark the letter used
    $order .= $letter;
    delete $avail{$letter};
    # Remove the letter
    foreach my $remove (grep { exists $deps{$_}{$letter} } keys %deps) {
        delete $deps{$remove}{$letter};
        # If no dependencies left, mark it available
        if (not %{$deps{$remove}}) {
            delete $deps{$remove};
            $avail{$remove} = ();
        }
    }
}

say $order;
