#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

our @position = map { m/(\d+)$/; $1 } <>;
our @score = (0) x @position;
our $roll_count = 0;

# Rolls the die and returns the result
sub roll {
    return $roll_count++ % 100 + 1;
}

my $turn = 0;                           # Whose turn it is
while (1) {
    $position[$turn] += &roll foreach 1..3;
    $position[$turn] -= 10 while $position[$turn] > 10;
    $score[$turn] += $position[$turn];
    last if $score[$turn] >= 1000;
    $turn++; $turn %= @position;        # Next player's turn
}

print $roll_count * $score[1-$turn], "\n";
