#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

sub bin2dec {
    return unpack("N", pack("B32", substr("0" x 32 . shift, -32)));
}

my @O2generator = map { chomp; [ split // ] } <>;
my @CO2scrubber = @O2generator;

foreach my $bit (0..$#{$O2generator[0]}) {
    my $O2zeroes = scalar grep { not $_ } map { $$_[$bit] } @O2generator;
    my $O2bit = int ($O2zeroes <= @O2generator / 2);
    @O2generator = grep { $$_[$bit] eq $O2bit } @O2generator
        if @O2generator > 1;

    my $CO2zeroes = scalar grep { not $_ } map { $$_[$bit] } @CO2scrubber;
    my $CO2bit = int ($CO2zeroes > @CO2scrubber / 2);
    @CO2scrubber = grep { $$_[$bit] eq $CO2bit } @CO2scrubber
        if @CO2scrubber > 1;
}

my $O2rating = &bin2dec(join('', @{$O2generator[0]}));
my $CO2rating = &bin2dec(join('', @{$CO2scrubber[0]}));

print $O2rating * $CO2rating, "\n";
