#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

sub bin2dec {
    return unpack("N", pack("B32", substr("0" x 32 . shift, -32)));
}

my @zeroes;
my $count = 0;
while (my $line = <>) {
    $count++;
    $zeroes[pos($line)-1]++ while $line =~ m/0/g;
}

my (@gamma) = map { int ($_ < $count / 2) } @zeroes;
my (@epsilon) = map { 1 - $_ } @gamma;

my $gamma = &bin2dec(join('', @gamma));
my $epsilon = &bin2dec(join('', @epsilon));

print $gamma * $epsilon, "\n";
