#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

our $enabler = 1;
our $sum = 0;
foreach (map { m/(?:mul\(\d{1,3},\d{1,3}\)|do\(\)|don't\(\))/g } <>) {
    /do\(\)/    && do { $enabler = 1; next; };
    /don't\(\)/ && do { $enabler = 0; next; };
    if ($enabler) {
        m/(\d+),(\d+)/;
        $sum += $1 * $2;
    }
}
print "${sum}\n";

