#!/usr/bin/perl

use 5.8.1;
use strict;
use warnings 'all';

our ($lower, $upper) = map { chomp; split /-/ } <>;

my $count = (grep { m/^0*1*2*3*4*5*6*7*8*9*$/ } # Digits must not descend
             grep { m/(\d)\1/ }                 # 2 identical adjacent digits
             $lower..$upper);
print "${count}\n";

__DATA__

# This version takes more lines, but actually runs a bit faster:

my $count = 0;
foreach ($lower..$upper) {
    #next if not m/^\d{6}$/;                  # Sanity check
    next if not m/(\d)\1/;                    # 2 adjacent digits are the same
    next if not m/^0*1*2*3*4*5*6*7*8*9*$/;    # Digits must not descend
    $count++;
}
print "${count}\n";
