#!/usr/bin/perl

use v5.36.0;    # Implies strict + warnings

# Just count how many times each word appears; if only once then that's the base
our %seen;
$seen{$_}++ foreach map { m/([[:alpha:]]+)/g } <>;
our %flip = reverse %seen;
say $flip{'1'};
